# environment.yml
name: quantms-rescoring
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9,<3.12
  - click
  - pyopenms>3.1.0
  - pandas >=1
  - numpy>=1.25
  - ms2rescore=3.2.0.post1
  - deepLC>=3.0
  - psm-utils
  - scipy
  - pygam
  - protobuf
  - pytest
  - ms2pip>=4.0
  - pip:
    - peptdeep==1.4.0
